services:
  - type: web
    name: jamhuuriyo-library-khayrre-yare
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/books
    autoDeployTrigger: commit
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_MAX_POOL_SIZE
        value: "3"
      - key: DB_MIN_IDLE
        value: "0"
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://jamhuuriyo-library-khayrre-yare.onrender.com
      - key: JPA_SHOW_SQL
        value: "false"
      - key: ADMIN_NAME
        value: Jamhuuriyo Library Administrator
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
